### PR TITLE
Fix relative path to ciDict.json

### PR DESCRIPTION
**Pull request by anastasds**
# Description

Pulling the latest release and running my local Rake task fails with

```
/Users/me/.rvm/gems/ruby-2.5.7/gems/cucumber-create-meta-6.0.3/lib/cucumber/create_meta.rb:10:in `read': No such file or directory @ rb_sysopen - /Users/me/.rvm/gems/ruby-2.5.7/gems/cucumber-create-meta-6.0.3/lib/cucumber/../../../ciDict.json (Errno::ENOENT)
```

Running

```
wget https://raw.githubusercontent.com/cucumber/create-meta/main/ciDict.json
```

in `/Users/me/.rvm/gems/ruby-2.5.7/gems/` fixes the issue. I believe I found where a relative path is being constructed incorrectly.

# Motivation & context

Fix the gem.

## Type of change

- Bug fix (non-breaking change which fixes an issue)

## Note to other contributors

None

## Update required of cucumber.io/docs

Not required

# Checklist:

- [X] I have read the [**CONTRIBUTING**](../CONTRIBUTING.md) document.
- [X] My code follows the code style of this project.
- [ ] I have added tests to cover my changes.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added an entry to the "Unreleased" section of the [**CHANGELOG**](../CHANGELOG.md), linking to this pull request.

### CODE REVIEW

**Comment by tsellers-r7** [comment]
We've seen the same breaking error. It would seem to be the correct number of directories to climb.. it is possible that the file is just missing from the gem since it is not under `ruby/`?

**Comment by orien** [comment]
`ciDict.json` is no-longer included in the Gem package: https://my.diffend.io/gems/cucumber-create-meta/6.0.2/6.0.3

**Comment by aurelien-reeves** [comment]
Thanks for the report, and the PR.
Indeed, there is a regression here. Sorry for that

I take a look ASAP

**Comment by aslakhellesoy** [comment]
Hi @anastasds,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber

**Comment by aurelien-reeves** [comment]
Thanks a lot for the quick report, and once again, sorry for that regression.

A new version, v6.0.4, has just been released and should fix the issue.

I have opened an issue to go further with that `ciDict.json` file.

**Pull request merged**
